### ISSUE TITLE
Scrapey timeout after login attempt 

### ISSUE THREAD

**Issue by ScottWorks** [ScottWorks/Scrapey-CLI#4]
For whatever reason Scrapey gets stuck after attempting to login, the 60 second timeout is exceeded and the program hangs.The solution should be to gracefully exit and prompt a restart.

**Comment by ScottWorks** [comment]
`
⠲ Navigating to solutions page.{ TimeoutError: Navigation Timeout Exceeded: 60000ms exceeded
    at Promise.then (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/FrameManager.js:1276:21)
  -- ASYNC --
    at Frame.<anonymous> (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.waitForNavigation (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/Page.js:644:49)
    at Page.<anonymous> (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/helper.js:145:23)
    at /home/corvo/Projects/Developer/Node/Scrapey/cmds/puppeteer.js:40:18
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
⠳ Navigating to solutions page.(node:12711) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 60000ms exceeded
    at Promise.then (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/FrameManager.js:1276:21)
  -- ASYNC --
    at Frame.<anonymous> (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.waitForNavigation (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/Page.js:644:49)
    at Page.<anonymous> (/home/corvo/Projects/Developer/Node/Scrapey/node_modules/puppeteer/lib/helper.js:145:23)
    at /home/corvo/Projects/Developer/Node/Scrapey/cmds/puppeteer.js:40:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12711) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Navigating to solutions page.^
`
